#' Default DEM from the floodam-ead package
#'
#' This is the default DEM generated by the function `generate_DEM` located in
#' the data-raw folder of the package source code, with default arguments.
#'
#' @format  A `PackedSpatRaster` object, use 'terra::rast()' to unpack it.
#' @source https://gitlab.irstea.fr/flood-appraisal/floodam/floodam-ead
#'
#' @examples
#' data("floodam_ead_dem", package = "rsic2")
#' floodam_ead_dem
#' terra::rast(floodam_ead_dem)
"floodam_ead_dem"
